name: Hello World Workflow
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Back-End Developers"
      - run: python --version
      - run: echo "Developer Tina"
